{
 "title": "dashboard-proj-iot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New panel",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Dashboard de Monitoramento de Qualidade da Água Utilizando Tecnologia IoT\n\n## Monitoramento de Temperatura da Água nos Reservatórios (°C)\n**Sensores:** DS18B20 (Sensor 1, 2 e 3)\n\nEste painel é dedicado ao monitoramento contínuo e preciso da temperatura da água em três pontos estratégicos dos reservatórios. A temperatura é um parâmetro fundamental, pois exerce influência direta sobre processos químicos, biológicos e na eficiência de tratamentos. O acompanhamento em tempo real permite a identificação imediata de flutuações anômalas, auxiliando na prevenção de eventos como a proliferação de microrganismos ou falhas no sistema de controle ambiental.\n\n## Visualização em Tempo Real do pH (Medidores Gauge)\n**Sensores:** PH-4502C (Sensor 1, 2 e 3)\n\nApresenta as medições instantâneas de pH através de uma visualização clara e intuitiva do tipo medidor (gauge). Esta representação permite uma leitura rápida e precisa do estado atual do sistema. Os mostradores são configurados com indicações visuais distintas para as faixas operacionais definidas - normal, alerta e crítico - facilitando o monitoramento contínuo e a identificação imediata de qualquer desvio dos parâmetros de qualidade estabelecidos.\n\n## Série Temporal do pH - Histórico de Variações (Últimas 5 Minutos)\n**Sensores:** PH-4502C (Sensor 1, 2 e 3)\n\nEste componente exibe o histórico recente das variações de pH, capturado em um modelo de série temporal (time series). Os dados dos três sensores são atualizados e registrados a intervalos de cinco minutos, fornecendo um panorama temporal consistente e detalhado. Esta visualização é essencial para a análise de tendências, permitindo aos operadores identificar padrões, sazonalidades ou alterações graduais na qualidade da água que não seriam perceptíveis em leituras pontuais.\n\n## Monitoramento da Temperatura Meteorológica da Região (São Paulo)\n**Fonte de Dados:** API OpenWeather integrada ao InfluxDB 2.x\n\nEste painel consolida e exibe a temperatura meteorológica atual da região de São Paulo, obtida através da integração com a API OpenWeather. Os dados são armazenados e gerenciados no banco de dados de séries temporais InfluxDB 2.x. A correlação entre as condições climáticas externas e os parâmetros internos da água é crucial para uma análise contextualizada, ajudando a discernir entre variações induzidas pelo ambiente externo e aquelas geradas por fatores internos do sistema."
   }
  },
  {
   "title": "Visualização em Tempo Real do pH (Medidores Gauge)",
   "type": "gauge",
   "description": "Monitoramento  Gauge dos sensores 1, 2 e 3 em tempo real ",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS 'ph_equip_01' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_01'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS 'ph_equip_02' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_02'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS 'ph_equip_03' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_03'"
    }
   ]
  },
  {
   "title": "Temperatura Meteorológica da Região (São Paulo)",
   "type": "stat",
   "description": "Valor da temperatura meteorológica em São Paulo. Fonte: OpenWeather",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"location_name\", \"temperature\", \"time\" FROM \"meteorologia\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "Monitoramento de Temperatura da Água nos Reservatórios (°C)",
   "type": "bargauge",
   "description": "Monitoramento de Temperatura da Água nos Reservatórios (°C)",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"temperatura\" AS 'temp_equip_01' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND equipamento = 'equipamento_01'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"temperatura\" AS 'temp_equip_02' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND equipamento = 'equipamento_02'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"temperatura\" AS 'temp_equip_03' FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND equipamento = 'equipamento_03'"
    }
   ]
  },
  {
   "title": "Série Temporal do pH - Histórico de Variações (Últimas 5 Minutos)",
   "type": "timeseries",
   "description": "Monitoramento do valor pH dos sensores 01, 02 e 03 atualizado de 5 em 5 minutos.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS \"ph_equip_01\", \"equipamento\", \"time\" FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_01'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS \"ph_equip_02\", \"equipamento\", \"time\" FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_02'"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT \"ph\" AS \"ph_equip_03\", \"equipamento\", \"time\" FROM \"equipamentos\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"equipamento\" = 'equipamento_03'"
    }
   ]
  }
 ]
}